#! /bin/sh

# set the cursor on inactive areas
xsetroot -cursor_name left_ptr

## Bspwm config

# General config
bspc config border_width        2
bspc config window_gap          4

bspc config top_padding         20
bspc config -m CRT1 top_padding 0
bspc config split_ratio         0.52
bspc config borderless_monocle  true
bspc config gapless_monocle     true
bspc config focus_by_distance   true
bspc config focus_follows_pointer false


# Colors
bspc config normal_border_color "#332d29"
bspc config active_border_color "#003366" #"#817267"
bspc config focused_border_color "006699"  # "#504339"
bspc config presel_border_color "#9a875f"
bspc config urgent_border_color "#9f7155"
bspc config focused_locked_border_color "#9a875f"
bspc config normal_frame_opacity 0.0
bspc config focused_frame_opacity 0.1


# Workspaces
monitors=$(bspc query -M | wc -l)
if [ $monitors == 1 ]; then
    bspc monitor -d 1 2 3 4 5
else
    # Set the monitors properly
    xrandr --output CRT1 --off && xrandr --output CRT1 --mode 1024x768 --right-of LVDS
    i=1
    for monitor in $(bspc query -M); do
        bspc monitor $monitor \
            -n "$i" \
            -d $i/{1,2,3}
        let i++
    done
fi

# Rules
bspc rule -a google-chrome-unstable desktop=^2
bspc rule -a Thunar floating=on
bspc rule -a Birdie floating=on
bspc rule -a corebird floating=on
bspc rule -a urxvt floating=on
bspc rule -a xfce4-panel sticky=on


## Auto start
#############

# set background
~/dotfiles/bin/set_bg &
# Authentication Agent
/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &
# Network Applet
nm-applet &
# Language
setxkbmap -layout us,ar -option grp:alt_shift_toggle
# Compton
compton -b --config ~/.compton.conf &
# Lemonbar
~/dotfiles/bspwm_bar/run.sh &
# Hide mouse cursor when idle
unclutter -root -idle 1 &
# Notification wrapper
dunst -conf dunst/dunstrc &
# Sound applet
pnmixer &
# Change keyboard repeating rate
xset r rate 250 25 &
# Rofi launcher (dmenu replacement)
rofi -key-run mod4+d&
# Run rxvt daemon
urxvtd &
# Trayer
sleep 3; trayer  --width 50 --widthtype pixel --edge top --height 14 --align right  --transparent true --tint 0xff1d1f21 --alpha 0 --distance 5 --distancefrom top --margin 5
# Xfce panel
# sleep 3; xfce4-panel --disable-wm-check&
# Num lock on
numlockx &
